### ISSUE TITLE
"To Do" bei der Sektion VSCode ist nur eine Anmerkung für Sie selbst, richtig?

### ISSUE THREAD

**Issue by Leleat** [elektrobohemian/EinrichtungArbeitsplatzInformatikStudium#1]
[o.g. Stelle](https://github.com/elektrobohemian/EinrichtungArbeitsplatzInformatikStudium#installation-von-visual-studio-code)

**Comment by elektrobohemian** [comment]
exakt, es handelt sich noch um "work in progress"!
