### ISSUE TITLE
Überschriften

### ISSUE THREAD

**Issue by self-confusion-MH** [elektrobohemian/EinrichtungArbeitsplatzInformatikStudium#2]
Die Überschriften könnten etwas mehr herausstechen, auf den ersten Blick könnte Verwirrung entstehen.
Ansonsten ist das Tutorial einfach zu verstehen. #

**Comment by elektrobohemian** [comment]
super, wenn es da keine Fragen gibt. ich schaue mal, ob ich die gliederung anders gestalten kann. bezüglich der formatierung kann ich es ja nicht bei github beeinflussen :-/

**Comment by self-confusion-MH** [comment]
Alles klar, viel Erfolg ;)
